modLoader="javafml"
loaderVersion="[24,)"
[[mods]]
modId="offlinetweaker"
version="${version}"
displayName="OfflineTweaker"
displayURL="https://github.com/ZekerZhayard/OfflineTweaker"
authors="xfl03, ZekerZhayard"
description='''
A mod to make WLAN server offline.
'''
[[dependencies.offlinetweaker]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.offlinetweaker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,)"
    ordering="NONE"
    side="CLIENT"
